version: "3"
services:
  scheduler:
    volumes:
      - ./dbt/dbt_project:/usr/local/airflow/dbt/dbt_project:rw
      - ./logs:/usr/local/airflow/logs:rw
      - ./config:/usr/local/airflow/config:rw
      - ../ingestion:/usr/local/airflow/ingestion:rw
      - ../data:/usr/local/airflow/data:rw

  webserver:
    volumes:
      - ./dbt/dbt_project:/usr/local/airflow/dbt/dbt_project:rw
      - ./logs:/usr/local/airflow/logs:rw
      - ./config:/usr/local/airflow/config:rw
      - ../ingestion:/usr/local/airflow/ingestion:rw
      - ../data:/usr/local/airflow/data:rw

  triggerer:
    volumes:
      - ./dbt/dbt_project:/usr/local/airflow/dbt/dbt_project:rw
      - ./logs:/usr/local/airflow/logs:rw
      - ./config:/usr/local/airflow/config:rw
      - ../ingestion:/usr/local/airflow/ingestion:rw
      - ../data:/usr/local/airflow/data:rw